### ISSUE TITLE
Setting initial value for single choice with items result of API call

### ISSUE THREAD

**Issue by dhurbhat** [lcuis/search_choices#96]
Hello - I'm new to Dart & Flutter; I'm using `search_choices` modeled after the example Single Choice with http based REST API call for paginated menu items.  BTW: I'm using FlutterFlow and have `search_choices` as a Custom Widget.
The basic display of drop down, paginated list of items, search all work well - and after selecting an item, I can see it displayed in the DDLB.... what I'm missing are couple of things:

1. How do I set the initial value?  For instance, lets say, that I select item #x, store this in a Firebase db, retrieve it and then want to display this in the `search_choices` widget.  How do I do this?  I've tried to set `selectedValueFuture` with a JSON object that would resemble an item from the API call, I get a JSON error: complains of setting an int with a string.  I don't understand this error... 
2. How can seed the search box so that when there is an initial value, the widget will "auto navigate" ?
3. I've tried the displayItem function (exact copy of what's in the example) - while it shows the radio buttons for each item, the radio button for selected item isn't active.  What else might I be missing?

Appreciate any pointers / help.
PS: apologies for creating an issue - didn't see any community or discord channel for "noob" / "I need help"...

**Comment by lcuis** [comment]
Hello @dhurbhat ,

Thanks for your issue. I will try to answer even though, I am not familiar with FlutterFlow. I hope my answers will still be valid.

Indeed, there is no discussion tab nor any discord for this repository. I will think about it, thanks for the suggestion.

1. I believe that the following code works with the example `Single dialog paged future`:
```dart
value: jsonDecode('{"id": 1, "country": "Åland Islands", "capital": "Mariehamn", "continent": "Europe", "population": 11709}'),
```
The idea is that what is expected is not the json but the map output by jsonDecode.

2. In the single case, your need may be addressed by using the example `Single dialog open and set search terms`. However, this will not allow the user to directly see the other possible values within the dialog. You may prefer the possibility to scroll to the selected value instead. Is it?

4. I just tried adding the `displayItem` from the `Single done button dialog` example into the `Single dialog paged future` example and I do get a selected radio button when the item is selected:
```dart
SearchChoices.single(
        value: selectedValueSingleDialogPagedFuture,
        hint: kIsWeb ? "Example not for web" : "Select one capital",
        searchHint: "Search capitals",
        onChanged: kIsWeb
            ? null
            : (value) {
                setState(() {
                  selectedValueSingleDialogPagedFuture = value;
                });
              },
        isExpanded: true,
        itemsPerPage: 10,
        currentPage: currentPage,
        displayItem: (item, selected) {
          return (Row(children: [
            selected
                ? const Icon(
              Icons.radio_button_checked,
              color: Colors.grey,
            )
                : const Icon(
              Icons.radio_button_unchecked,
              color: Colors.grey,
            ),
            const SizedBox(width: 7),
            Expanded(
              child: item,
            ),
          ]));
        },
        selectedValueWidgetFn: (item) {
          return (Center(
              child: Card(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(4),
                    side: const BorderSide(
                      color: Colors.grey,
                      width: 1,
                    ),
                  ),
                  margin: const EdgeInsets.all(1),
                  child: Padding(
                    padding: const EdgeInsets.all(6),
                    child: Text(item["capital"]),
                  ))));
        },
        futureSearchFn: (String? keyword, String? orderBy, bool? orderAsc,
            List<Tuple2<String, String>>? filters, int? pageNb) async {
          String filtersString = "";
          int i = 1;
          filters?.forEach((element) {
            filtersString += "&filter$i=${element.item1},${element.item2}";
            i++;
          });
          Response response = await get(Uri.parse(
                  "https://searchchoices.jod.li/exampleList.php?page=${pageNb ?? 1},10${orderBy == null ? "" : "&order=$orderBy,${orderAsc ?? true ? "asc" : "desc"}"}${(keyword == null || keyword.isEmpty) ? "" : "&filter=capital,cs,$keyword"}$filtersString"))
              .timeout(const Duration(
            seconds: 10,
          ));
          if (response.statusCode != 200) {
            throw Exception("failed to get data from internet");
          }
          dynamic data = jsonDecode(response.body);
          int nbResults = data["results"];
          List<DropdownMenuItem> results = (data["records"] as List<dynamic>)
              .map<DropdownMenuItem>((item) => DropdownMenuItem(
                    value: item,
                    child: Card(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4),
                        side: const BorderSide(
                          color: Colors.blue,
                          width: 1,
                        ),
                      ),
                      margin: const EdgeInsets.all(10),
                      child: Padding(
                        padding: const EdgeInsets.all(6),
                        child: Text(
                            "${item["capital"]} - ${item["country"]} - ${item["continent"]} - pop.: ${item["population"]}"),
                      ),
                    ),
                  ))
              .toList();
          return (Tuple2<List<DropdownMenuItem>, int>(results, nbResults));
        },
        futureSearchOrderOptions: {
          "country": {
            "icon": Wrap(children: const [
              Icon(Icons.flag),
              Text(
                "Country",
              )
            ]),
            "asc": true
          },
          "capital": {
            "icon": Wrap(
                children: const [Icon(Icons.location_city), Text("Capital")]),
            "asc": true
          },
          "continent": const {"icon": "Continent", "asc": true},
          "population": {
            "icon":
                Wrap(children: const [Icon(Icons.people), Text("Population")]),
            "asc": false
          },
        },
        futureSearchFilterOptions: {
          "continent": const {
            "icon": Text("Continent"),
            "exclusive": true,
            "values": [
              {"eq,Africa": "Africa"},
              {"eq,Americas": "Americas"},
              {"eq,Asia": "Asia"},
              {"eq,Australia": "Australia"},
              {"eq,Europe": "Europe"},
              {"eq,Oceania": "Oceania"}
            ]
          },
          "population": {
            "icon":
                Wrap(children: const [Icon(Icons.people), Text("Population")]),
            "exclusive": true,
            "values": [
              {
                "lt,1000":
                    Wrap(children: const [Icon(Icons.person), Text("<1,000")])
              },
              {
                "lt,100000": Wrap(
                    children: const [Icon(Icons.person_add), Text("<100,000")])
              },
              {
                "lt,1000000": Wrap(children: const [
                  Icon(Icons.nature_people),
                  Text("<1,000,000")
                ])
              },
              {
                "gt,1000000": Wrap(
                    children: const [Icon(Icons.people), Text(">1,000,000")])
              },
              {
                "gt,10000000": Wrap(children: const [
                  Icon(Icons.location_city),
                  Text(">10,000,000")
                ])
              },
            ]
          },
        },
        closeButton: (selectedItemsDone, doneContext) {
          return Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              SizedBox(
                height: 25,
                width: 48,
                child: (ElevatedButton(
                    onPressed: () {
                      Navigator.pop(doneContext);
                      setState(() {});
                    },
                    child: const Icon(
                      Icons.close,
                      size: 17,
                    ))),
              ),
            ],
          );
        },
      )
```
Maybe you'd like to share your code here to see if there is an issue I can help with?
Otherwise, one way could be to check whether the item to display is equivalent to the selected item as kept from outside the widget?

**Comment by dhurbhat** [comment]
It turns out that the issues with `jsonDecode` that I was facing had to do with Dart class definition and the way I was initializing some of the variables.  I've fixed that; and also added the `displayItem` function and the radio buttons are now functioning ( I think they weren't working before 'cause of other initialization issues).  

Thank you very much for this **wonderful widget** !

**Comment by lcuis** [comment]
Thanks a lot for your message and your confirmation @dhurbhat !

**Comment by phranklins** [comment]
@dhurbhat I'm actually trying to add this as a custom widget in Flutterflow and just confused since I'm new to this. Would you be able to share your custom widget code or give insight into how you added it to Flutterflow? Thank you!

**Comment by dhurbhat** [comment]
@phranklins - I started with [FF Custom Widgets](https://docs.flutterflow.io/customizing-your-app/custom-widgets) doc.  Then,
1.  I followed `search_choices` example for building the list from the result of an API call.  
2. I tweaked the parameters to the Stateful Widget in `search_choices` custom widget so that the API call would work for my widget.
3. I placed my custom widget on a page and quickly learned that you need to use FF Local State to read and write value from your custom widget.  So I created appropriate FF local state variable for this.

Hope that helps.

**Comment by phranklins** [comment]
Thank you, @dhurbhat! You advice on number 3 was super helpful in figuring out how to read/write the selection in general for this package in Flutterflow. Unfortunately I still can't get the API to work for web (I know the example isn't built for it), but I added a proxy to make it work, but I keep getting a, **Error: Expected a value of type 'String', but got one of type '_JsonMap'**, even when using the example directly. Do you try to implement this over web? If not, no worries. I'll post a separate issue here to troubleshoot. Thanks!

**Comment by dhurbhat** [comment]
@phranklins - where are you receiving this error? Typically, API responses are JSON - so are you using something like `        dynamic data = jsonDecode(response.body);` ?

The above line is directly from API invocation in `search_choices` `futureSearchFn`... the standard example is what works for me... snipped here:
```
        futureSearchFn: (String? keyword, String? orderBy, bool? orderAsc,
            List<Tuple2<String, String>>? filters, int? pageNb) async {
          Response response = await get(Uri.parse(
                  "${widget.collegeAPIUrl}?page=${pageNb ?? 1}&per_page=25${(keyword == null || keyword.isEmpty) ? "" : "&school.name=$keyword"}"))
              .timeout(const Duration(
            seconds: 10,
          ));
          if (response.statusCode != 200) {
            throw Exception("failed to get data from internet");
          }
          dynamic data = jsonDecode(response.body);
          int nbResults = data["metadata"]["total"];
          List<DropdownMenuItem> results = (data["results"] as List<dynamic>)
```
Maybe if you post your sample code & error...

**Comment by phranklins** [comment]
Thanks @dhurbhat. I actually just used the code straight from the example, but added a CROS proxy so that it would work with web. That's where I got the JSON error. When I do a little more investigation, I'll create a new ticket and maybe tag you since you got it working. 

As for the initial choice being selected, this thread was helpful for me to solve that for using search_choices in a non-API call single dialog way. Thank you!

**Comment by phranklins** [comment]
Hi @dhurbhat! Sorry to bother you again. I figured out my issues from before, but now I'm running into the same issue you did with trying to pull a previous selection stored in Firebase to prepopulate the dropdown/search term. Just like you, I get the error, "Expected a value of type 'int', but got one of type 'String'. I stored the json from the api call as JSON in Local State / App State like you mentioned, but when setting selectedValueSingleDialogPagedFuture to the value, I receive the error. Did you do anything to save the json in local state to firebase and how did you reference the json to pull it to prepopulate the dropdown?  Thank you!

**Comment by dhurbhat** [comment]
If I recall correctly, I had to use jdonencode on storing and use
jsondecode on setting… especially in fire base.

Hope that helps!
Sheshadri

**Comment by phranklins** [comment]
Yes! I originally did include the decode and encode, but I had stored it in local state as a json. Keeping it as string worked fine. That's exactly what worked to store the json and then recall it to prepopulate the dropdown. I couldn't get it to pretype that response once you clicked on the dropdown, but this works for now. Thank you!
